#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL

param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500     # Motor timeout in milliseconds

param set-default CA_AIRFRAME 2        
param set-default SYS_AUTOSTART 10152     # Loads the Otter Airframe 10152_gazebo-classic_otter

param set-default CA_ROTOR_COUNT 5

param set-default CA_ROTOR0_PX 0.375      # Top Right 1
param set-default CA_ROTOR0_PY 0.375	 
param set-default CA_ROTOR0_PZ -0.095465
param set-default CA_ROTOR0_KM 0.0197     # 6 CCW +
param set-default CA_ROTOR0_CT 22.4

param set-default CA_ROTOR1_PX -0.375    # Bottom Left 2
param set-default CA_ROTOR1_PY -0.375
param set-default CA_ROTOR1_PZ -0.095465
param set-default CA_ROTOR1_KM 0.0197    # 6 CCW +
param set-default CA_ROTOR1_CT 22.4

param set-default CA_ROTOR2_PX 0.375     # Top Left 3
param set-default CA_ROTOR2_PY -0.375
param set-default CA_ROTOR2_PZ -0.095465
param set-default CA_ROTOR2_KM -0.0197   # 6 CW -
param set-default CA_ROTOR2_CT 22.4

param set-default CA_ROTOR3_PX -0.375    # Bottom Right 4
param set-default CA_ROTOR3_PY 0.375
param set-default CA_ROTOR3_PZ -0.095465
param set-default CA_ROTOR3_KM -0.0197   # 6 CW -
param set-default CA_ROTOR3_CT 22.4

param set-default CA_ROTOR4_AX 1         # Changing axis to along X
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0
param set-default CA_ROTOR4_PX 0
param set-default CA_ROTOR4_PY 0
param set-default CA_ROTOR4_PZ 0 #-0.035
param set-default CA_ROTOR4_KM 0.0196 #-0.0196
param set-default CA_ROTOR4_CT 33.72

param set-default CA_SV_CS_COUNT 6        # 6 Control Surfaces

param set-default CA_SV_CS1_TYPE 1        # Left Aileron
param set-default CA_SV_CS1_TRQ_R 0.5

param set-default CA_SV_CS0_TYPE 2        # Right Aileron
param set-default CA_SV_CS0_TRQ_R -0.5    # + CW, - CCW

param set-default CA_SV_CS2_TYPE 3        # Right Elevator
param set-default CA_SV_CS2_TRQ_P 0.5

param set-default CA_SV_CS3_TYPE 3        # Left Elevator
param set-default CA_SV_CS3_TRQ_P 0.5

param set-default CA_SV_CS4_TYPE 4        # Right Rudder
param set-default CA_SV_CS4_TRQ_Y 0.5

param set-default CA_SV_CS5_TYPE 4        # left Rudder
param set-default CA_SV_CS5_TRQ_Y 0.5

param set-default PWM_MAIN_FUNC1 101 # Motor 0
param set-default PWM_MAIN_FUNC2 102 # Motor 1
param set-default PWM_MAIN_FUNC3 103 # Motor 2
param set-default PWM_MAIN_FUNC4 104 # Motor 3
param set-default PWM_MAIN_FUNC5 105 # Motor Pusher
param set-default PWM_MAIN_FUNC6 201 # Right Aileron
param set-default PWM_MAIN_FUNC7 202 # Left Aileron
param set-default PWM_MAIN_FUNC8 203 # Right Elevator
param set-default PWM_MAIN_FUNC9 204 # Left Elevator
param set-default PWM_MAIN_FUNC10 205 # Right Rudder
param set-default PWM_MAIN_FUNC11 206 # Left Rudder

######### FW: Fixed Wing Mode ############

param set-default FW_AIRSPD_MAX 21    # Max Speed
param set-default FW_AIRSPD_MIN 12    # Min Speed

param set-default FW_AIRSPD_STALL 11  # Stall
param set-default FW_THR_ASPD_MAX 1.0 # Max throttle allowed at max airspeed 

param set-default FW_THR_MAX 1.0    # Max throttle in FW mode
param set-default FW_THR_MIN 0.05   # Min Throttle in FW mode

# TRIM CONDITIONS

param set-default FW_PSP_OFF 5.3      # 5 Degrees trim
param set-default FW_THR_TRIM 0.5  # Cruise throttle at trim
param set-default FW_AIRSPD_TRIM 14 # Cruise

param set-default FW_P_LIM_MAX 25   # Max nose up pitch angle
param set-default FW_T_CLMB_MAX 3.0 # Max climb rate m/s

param set-default FW_P_LIM_MIN -25  # Max nose down pitch angle
param set-default FW_T_SINK_MAX 2.7 # max descent rate m/s

param set-default FW_T_SINK_MIN 2.2 # min sink rate m/s
param set-default FW_R_LIM 35       # Max bank angle 

# Pitch Rate
param set-default FW_PR_FF 0.2      # Pitch rate feedforward - improves pitch response
param set-default FW_PR_P 0.65       # Pitch rate P gain constant - how strongly it fights pitch rate errors 0.9

# Roll Rate
param set-default FW_RR_FF 0.1      # roll rate feedforward
param set-default FW_RR_P 0.3       # roll rate P gain constant

# Yaw Rate
param set-default FW_YR_FF 0.1      # yaw rate feedforward
param set-default FW_YR_P 0.3       # yaw rate proportional gain constant 

# TECS
param set-default FW_T_HRATE_FF 0.3   # Height rate feedforward
param set-default FW_T_VERT_ACC 7.0   # Max vertical acceleration m/s²


########## MC: Multirotor mode ############				  
param set-defualt MAN_ARM_GESTURE 0
#param set-default MC_AIRMODE 2  # Enables airmode — R/P/Y (causing vertical control issue - test carefully)
param set-default MC_AIRMODE 1  # Enables airmode — R/P

param set-default MC_PITCHRATE_MAX 60.0
param set-default MC_ROLLRATE_MAX 60.0
param set-default MC_YAWRATE_MAX 60.0

param set-default MC_ROLLRATE_K 1.0      # Roll rate K gain
param set-default MC_PITCHRATE_K 1.0     # Pitch rate K gain
param set-default MC_YAWRATE_K 1.0       # Yaw rate K gain

param set-default MC_ROLLRATE_P 0.3      # Roll rate P gain 0.3
param set-default MC_PITCHRATE_P 0.2     # Pitch rate P gain 0.8
param set-default MC_YAWRATE_P 1.2         # Yaw rate P gain 2.0

param set-default MC_ROLLRATE_D 0.01     # Roll rate D gain
param set-default MC_PITCHRATE_D 0.01    # Pitch rate D gain
param set-default MC_YAWRATE_D 0.001     # Roll rate D gain 

param set-default MC_ROLLRATE_I 0.2      # Roll rate I gain 
param set-default MC_PITCHRATE_I 0.3     # Pitch rate I gain
param set-default MC_YAWRATE_I 0.4       # Yaw rate I gain

param set-default MC_ROLL_P 3.0          # Roll angle P gain 1.0
param set-default MC_PITCH_P 2.5        # Pitch angle P gain 1.0
param set-default MC_YAW_P 3.0             # Yaw angle P gain 

# Velocity Control
param set-default MPC_XY_VEL_P_ACC 1.30
param set-default MPC_XY_VEL_D_ACC 0.35

param set-default MPC_Z_VEL_P_ACC 4

param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_Z_VEL_I_ACC 2.5

param set-default MPC_XY_VEL_D_ACC 0.35
param set-default MPC_Z_VEL_D_ACC 0.0

param set-default MPC_XY_VEL_MAX 4.0
param set-default MPC_XY_CRUISE 4.0

param set-default MPC_XY_P 0.04    # 0.2 Horizontal Position
param set-default MPC_Z_P 1.0     # Vertical Position

param set-default MPC_MAN_Y_MAX 25.0
param set-default MPC_MAN_Y_TAU 0.15

param set-default MPC_TILTMAX_AIR 20
param set-default MPC_MAN_TILT_MAX 20

param set-default MPC_THR_MIN 0.20
param set-defualt MPC_MANTHR_MIN 0.15
param set-default MPC_THR_HOVER 0.65

param set-default MIS_TAKEOFF_ALT 10     # Auto takeoff altitude meters
param set-default NPFG_PERIOD 8          # PFG path following period in seconds. Higher = gentler turns
param set-default NAV_ACC_RAD 40         # Waypoint acceptance radius

########## VTOL mode ############

param set-default VT_FWD_THRUST_EN 0     # Enables pusher motor assist during MC mode for forward flight
param set-default VT_FWD_THRUST_SC 1     # Pusher thrust scale factor during MC forward flight
param set-default VT_F_TRANS_THR 1.0     # Pusher throttle during forward transition

param set-default VT_ARSP_TRANS 14       # Transition airspeed
param set-default VT_ARSP_BLEND 10       # Blend start airspeed
param set-default VT_F_TRANS_DUR 15      # Forward transition duration

param set-default VT_B_TRANS_DUR 10      # Back transition duration
param set-default VT_TYPE 2              # Standard VTOL
param set-default MIS_YAW_TMT 15         # Time alotted before failling transition yaw
param set-default MIS_YAW_ERR 25         # Time alotted before failling transition yaw

########## Safety ############
RTL_RETURN_ALT 40.0
