#!/bin/sh
#
# @name Dragonfly Interceptor
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @maintainer Grant Howard <granthoward@uvic.ca>
#

. ${R}etc/init.d/rc.vtol_defaults

## VTOL
# Type
param set-default MAV_TYPE 20
param set-default VT_TYPE 0
param set-default CA_AIRFRAME 4

# No control surfaces
param set-default CA_SV_CS_COUNT 0
# No airspeed
param set-default FW_USE_AIRSPD 1
param set-default SYS_HAS_NUM_ASPD 1
param set-default FW_ARSP_SCALE_EN 0

# Transition time
param set-default VT_ARSP_TRANS 0.0
param set-default VT_ARSP_BLEND 0.0

param set-default VT_TRANS_MIN_TM 4.0
param set-default VT_F_TRANS_DUR 5.0
param set-default VT_F_TR_OL_TM 5.0

param set-default VT_B_TRANS_DUR 6.0
param set-default VT_B_DEC_MSS 2.5

param set-default VT_FW_MIN_ALT 15.0

# Differential Thrust
param set-default VT_FW_DIFTHR_EN 7

param set-default VT_FW_DIFTHR_S_P 0.75
param set-default VT_FW_DIFTHR_S_R 0.6
param set-default VT_FW_DIFTHR_S_Y 0.6

param set-default WV_EN 0
#Mixer 
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.13
param set-default CA_ROTOR0_KM 0.023
param set-default CA_ROTOR0_CT 15.0

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.13
param set-default CA_ROTOR1_KM 0.023
param set-default CA_ROTOR1_CT 15.0

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.13
param set-default CA_ROTOR2_KM -0.023
param set-default CA_ROTOR2_CT 15.0

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.13
param set-default CA_ROTOR3_KM -0.023
param set-default CA_ROTOR3_CT 15.0

#Sim specific
param set-default CA_AIRFRAME 0
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

#Temp for tuning
	param set-default MC_AIRMODE 2 #Set to 0 when tuning innerloop, 2 when tuned
	# param set-default MC_ACRO_EXPO 0
	# param set-default MC_ACRO_EXPO_Y 0
	# param set-default MC_ACRO_SUPEXPO 0
	# param set-default MC_ACRO_SUPEXPOY 0

##SYSTEMS
	#Power
	param set-default BAT1_N_CELLS 6
	param set-default BAT1_CAPACITY 2200
	param set-default BAT1_R_INTERNAL 0.01

	#Motor settings
	param set-default THR_MDL_FAC 0.6

	#Mission and safety
	param set-default COM_RC_LOSS_T 2 #Seconds of lost radio to trigger failsafe
	param set-default COM_RC_STICK_OV 30 #Stick treshold to revert to position mode

	#Logging settings
	param set-default SDLOG_PROFILE 27
	param set-default SDLOG_UTC_OFFSET -480

	#Filters

	#Multi-agent
	param set-default NAV_TRAFF_AVOID 0

##CONTROLLER TUNING
	#Rate controller
	param set-default MC_PITCHRATE_K 0.9
	param set-default MC_PITCHRATE_P 0.09
	param set-default MC_PITCHRATE_I 0.12
	param set-default MC_PITCHRATE_D 0.0025

	param set-default MC_ROLLRATE_K 0.9
	param set-default MC_ROLLRATE_P 0.09
	param set-default MC_ROLLRATE_I 0.12
	param set-default MC_ROLLRATE_D 0.0025
	# K to 0.7
	param set-default MC_YAWRATE_K 0.9
	param set-default MC_YAWRATE_P 0.12
	param set-default MC_YAWRATE_I 0.10
	param set-default MC_YAWRATE_D 0.01
	
	#Attitude controller
	param set-default MC_PITCH_P 3.5 
	param set-default MC_ROLL_P 3.5 
	param set-default MC_YAW_P 3.0
	
	#Position Controller
	param set-default MPC_TILTMAX_AIR 60
	param set-default MPC_MAN_TILT_MAX 60
	
	param set-default MPC_THR_HOVER 0.25
	param set-default MPC_VEL_MANUAL 20
	param set-default MPC_XY_VEL_MAX 25
	param set-default MPC_XY_CRUISE  25
	
	param set-default MPC_XY_VEL_P_ACC 2.15
	
	param set-default MPC_Z_VEL_P_ACC 3.5
	param set-default MPC_Z_VEL_I_ACC 2.5
	param set-default MPC_Z_VEL_D_ACC 0.8
	
	param set-default MPC_ACC_HOR 4.0
	
	param set-default MPC_Z_VEL_MAX_UP 5.0
	param set-default MPC_Z_VEL_MAX_DN 2.5
	
	param set-default MPC_Z_V_AUTO_UP 4.0
	param set-default MPC_Z_V_AUTO_DN 2.0
	param set-default MPC_LAND_SPEED 0.6
	
	param set-default MPC_YAW_MODE 3
	
	param set-default NAV_ACC_RAD 50.0 # Need greater rad for high-speed flight. Reduce for smaller missions
	
	#Max rates
	param set-default MC_ROLLRATE_MAX 75
	param set-default MC_PITCHRATE_MAX 75
	param set-default MC_YAWRATE_MAX 75
	param set-default MPC_YAWRAUTO_MAX 75

	#Max rates ACRO
	param set-default MC_ACRO_P_MAX 75
	param set-default MC_ACRO_R_MAX 75
	param set-default MC_ACRO_Y_MAX 60
	
	## Fixed Wing
	param set-default FW_PSP_OFF 15 # Set as needed. This is for std wing config.
	param set-default FW_P_RMAX_NEG 20.0
	param set-default FW_P_RMAX_POS 20.0
	param set-default FW_R_RMAX 20.0
	param set-default FW_Y_RMAX 20.0
	
	param set-default FW_P_LIM_MAX 35
	param set-default FW_P_LIM_MIN 0 # Set as needed. This is for std wing config.
	param set-default FW_R_LIM 40.0
	
	param set-default FW_THR_TRIM 0.35
	param set-default FW_THR_MAX 1.0
	param set-default FW_THR_MIN 0.1
	
	param set-default FW_T_CLMB_MAX 5.0
	param set-default FW_T_CLMB_R_SP 4.0
	param set-default FW_T_SINK_MAX 4.0
	param set-default FW_T_SINK_R_SP 3.0
	
	param set-default FW_T_HRATE_FF 0.3
	param set-default FW_T_I_GAIN_PIT 0.15
	
	param set-default FW_AIRSPD_STALL 15
	param set-default FW_AIRSPD_MIN 17
	param set-default FW_AIRSPD_TRIM 21
	param set-default FW_AIRSPD_MAX 30
	
	param set-default NAV_LOITER_RAD 80.0
	param set-default RTL_LOITER_RAD 80.0
	param set-default NPFG_PERIOD 9.0
	param set-default NPFG_SW_DST_MLT 0.60
	param set-default NPFG_ROLL_TC 0.75
	
	# Rate Control
	param set-default FW_PR_FF 0.1
	param set-default FW_PR_D 0.002
	param set-default FW_PR_I 0.1
	param set-default FW_PR_P 0.1
	
	param set-default FW_RR_FF 0.2
	param set-default FW_RR_D 0.002
	param set-default FW_RR_P 0.2
	
	param set-default FW_YR_P 0.10
	param set-default FW_YR_I 0.1
	param set-default FW_YR_D 0.002
	
##TANSMITTER
	#Modes
	param set-default RC_MAP_FLTMODE 6

	#Arm and kill
	param set-default RC_MAP_ARM_SW 5
	param set-default RC_MAP_KILL_SW 7
## SAFETY
	param set-default RTL_RETURN_ALT 30.0
