#!/bin/sh
#
# @name Dragonfly Interceptor
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Grant Howard <granthoward@uvic.ca>
#

. ${R}etc/init.d/rc.mc_defaults

#Mixer 
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.13
param set-default CA_ROTOR0_KM 0.023
param set-default CA_ROTOR0_CT 15.0

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.13
param set-default CA_ROTOR1_KM 0.023
param set-default CA_ROTOR1_CT 15.0

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.13
param set-default CA_ROTOR2_KM -0.023
param set-default CA_ROTOR2_CT 15.0

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.13
param set-default CA_ROTOR3_KM -0.023
param set-default CA_ROTOR3_CT 15.0

#Sim specific
param set-default CA_AIRFRAME 0
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

#Temp for tuning
	param set-default MC_AIRMODE 2 #Set to 0 when tuning innerloop, 2 when tuned
	# param set-default MC_ACRO_EXPO 0
	# param set-default MC_ACRO_EXPO_Y 0
	# param set-default MC_ACRO_SUPEXPO 0
	# param set-default MC_ACRO_SUPEXPOY 0

##SYSTEMS
	#Power
	param set-default BAT1_N_CELLS 6
	param set-default BAT1_CAPACITY 2200
	param set-default BAT1_R_INTERNAL 0.01

	#Motor settings
	param set-default THR_MDL_FAC 0.6

	#Mission and safety
	param set-default COM_RC_LOSS_T 2 #Seconds of lost radio to trigger failsafe
	param set-default COM_RC_STICK_OV 30 #Stick treshold to revert to position mode

	#Logging settings
	param set-default SDLOG_PROFILE 27
	param set-default SDLOG_UTC_OFFSET -480

	#Filters

	#Multi-agent
	param set-default NAV_TRAFF_AVOID 0

##CONTROLLER TUNING
	#Rate controller
	#K can increase to 1.2-1.3 if successful  
	param set-default MC_PITCHRATE_K 1.1
	param set-default MC_PITCHRATE_P 0.15 # 0.14
	param set-default MC_PITCHRATE_I 0.20 # 0.25
	param set-default MC_PITCHRATE_D 0.010
	# K can increase to 1.2-1.3 if successful  
	param set-default MC_ROLLRATE_K 1.1
	param set-default MC_ROLLRATE_P 0.15
	param set-default MC_ROLLRATE_I 0.20 # 0.25
	param set-default MC_ROLLRATE_D 0.010
	# K to 0.7
	param set-default MC_YAWRATE_K 0.7
	param set-default MC_YAWRATE_P 0.15
	param set-default MC_YAWRATE_I 0.15
	param set-default MC_YAWRATE_D 0.02
	
	#Attitude controller
	param set-default MC_PITCH_P 2.5 # 3.5
	param set-default MC_ROLL_P 2.5  # 3.5
	param set-default MC_YAW_P 1.5
	
	#Position Controller
	param set-default MPC_TILTMAX_AIR 65
	param set-default MPC_MAN_TILT_MAX 65
	
	param set-default MPC_THR_HOVER 0.25
	param set-default MPC_VEL_MANUAL 25
	param set-default MPC_XY_VEL_MAX 25
	param set-default MPC_XY_CRUISE  25
	
	param set-default MPC_XY_P 0.60
	param set-default MPC_XY_VEL_P_ACC 2.2
	param set-default MPC_XY_VEL_I_ACC 0.8
	param set-default MPC_XY_VEL_D_ACC 0.8
	
	param set-default MPC_Z_VEL_P_ACC 3.5
	param set-default MPC_Z_VEL_I_ACC 2.5
	param set-default MPC_Z_VEL_D_ACC 0.8
	
	param set-default MPC_ACC_HOR 4.0
	
	param set-default MPC_Z_VEL_MAX_UP 5.0
	param set-default MPC_Z_VEL_MAX_DN 2.5
	
	param set-default MPC_Z_V_AUTO_UP 4.0
	param set-default MPC_Z_V_AUTO_DN 2.0
	
	param set-default MPC_YAW_MODE 3
	
	param set-default NAV_ACC_RAD 100.0
	
	#Max rates
	param set-default MC_ROLLRATE_MAX 60
	param set-default MC_PITCHRATE_MAX 100
	param set-default MC_YAWRATE_MAX 75
	param set-default MPC_YAWRAUTO_MAX 75

	#Max rates ACRO
	param set-default MC_ACRO_P_MAX 65
	param set-default MC_ACRO_R_MAX 65
	param set-default MC_ACRO_Y_MAX 40

##TANSMITTER

	#Modes
	param set-default RC_MAP_FLTMODE 5
	param set-default COM_FLTMODE1 6 #Acro
	param set-default COM_FLTMODE2 8 #Stabilized
	param set-default COM_FLTMODE3 2 #Position
	param set-default COM_FLTMODE4 3 #Mission
	param set-default COM_FLTMODE5 5 #Return
	param set-default COM_FLTMODE6 4 #Hold

	#Rssi
	param set-default RC_RSSI_PWM_CHAN 12
	param set-default RC_RSSI_PWM_MAX 2000
	param set-default RC_RSSI_PWM_MIN 1000

	#Arm and kill
	param set-default RC_MAP_ARM_SW 6
	param set-default RC_MAP_KILL_SW 7
